"""
preprocess-reserve.py — build data-reserve.js from main_data_with_imbalance.csv.

WHY A SEPARATE FILE
===================
The Backtester's reserve-market feature needs the LV down-capacity prices
(`reserves_mfrr_downward_lv`, `reserves_afrr_downward_lv`). Rather than
regenerate data.js (which would risk drifting the frozen regression
arrays), we ship these as a separate optional file — exactly the pattern
used by data-afrr.js / data-afrr-15min.js. engine.js wraps the global
`RESERVE_DATA` if present and falls back to empty arrays if it's missing.

ALIGNMENT
=========
We align reserve prices to data.js's ISP indices BY TIMESTAMP:
  ts(i) = start_iso + offsets[i] * step_min minutes
then look up the CSV row at that exact timestamp. This is robust to
whatever NaN-row filtering preprocess.py applied — the indices always
line up with data.js regardless. A row with no CSV match (or a null
price) becomes JSON null → NaN in engine.js → "no reserve that ISP".

UNITS
=====
Reserve capacity prices are HOURLY (EUR/MW·h), constant across the four
15-min ISPs of each hour. The Backtester pays capacity income as
`price * awarded_MW * 0.25h` per ISP.

Run:  python preprocess-reserve.py
Then bump ?v=N on data-reserve.js in index.html.
"""

import json
import os

import numpy as np
import pandas as pd

CSV_PATH = "main_data_with_imbalance.csv"
DATA_JS_PATH = "data.js"
OUT_PATH = "data-reserve.js"

# LV down prices drive the Backtester reserve strategy; up prices are added
# so the Graphs "mFRR vs aFRR reserves" subtab can use a representative
# (up+down average) reserve price per market.
RES_COLS = {
    "reserve_mfrr_dn": "reserves_mfrr_downward_lv",
    "reserve_mfrr_up": "reserves_mfrr_upward_lv",
    "reserve_afrr_dn": "reserves_afrr_downward_lv",
    "reserve_afrr_up": "reserves_afrr_upward_lv",
}


def load_data_js_meta():
    with open(DATA_JS_PATH, "r", encoding="utf-8") as f:
        text = f.read()
    d = json.loads(text[text.index("{") : text.rindex("}") + 1])
    return d


def main():
    print("Reading data.js meta…", flush=True)
    meta = load_data_js_meta()
    n = meta["n"]
    step = meta["step_min"]
    offsets = meta["offsets"]
    start = pd.to_datetime(meta["start_iso"]).tz_localize(None)
    print(f"  data.js: n={n}, start={start}, step={step} min")

    print("Reading CSV reserve columns…", flush=True)
    df = pd.read_csv(CSV_PATH, usecols=["datetime_utc", *RES_COLS.values()])
    df["datetime_utc"] = pd.to_datetime(df["datetime_utc"])
    df = df.set_index("datetime_utc")
    # Drop any duplicate timestamps so reindex is unambiguous.
    df = df[~df.index.duplicated(keep="first")]

    # Target timestamp for every ISP index, then reindex (NaN where missing).
    target_ts = pd.DatetimeIndex(
        [start + pd.Timedelta(minutes=int(off) * step) for off in offsets]
    )

    def to_json_list(series):
        return [None if pd.isna(v) else round(float(v), 3) for v in series.to_numpy()]

    out = {"n": n}
    for key, col in RES_COLS.items():
        out[key] = to_json_list(df[col].reindex(target_ts))
        assert len(out[key]) == n, f"length mismatch for {key} vs data.js n"

    js = "// Auto-generated by preprocess-reserve.py — do not edit by hand.\n"
    js += "const RESERVE_DATA = " + json.dumps(out, separators=(",", ":")) + ";\n"
    js += "if (typeof module !== 'undefined') module.exports = RESERVE_DATA;\n"
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write(js)

    sz = os.path.getsize(OUT_PATH) / (1024 * 1024)
    print(f"  wrote {OUT_PATH}: {sz:.2f} MB")
    for key in RES_COLS:
        nn = sum(1 for v in out[key] if v is not None)
        print(f"  {key} non-null: {nn}/{n} ({100*nn/n:.1f}%)")
    for name, arr in [("mfrr_dn", out["reserve_mfrr_dn"]), ("afrr_dn", out["reserve_afrr_dn"])]:
        a = np.asarray([v for v in arr if v is not None], dtype=float)
        if len(a):
            print(
                f"  {name}: min={a.min():.2f} p50={np.percentile(a,50):.2f} "
                f"p90={np.percentile(a,90):.2f} max={a.max():.2f}"
            )


if __name__ == "__main__":
    main()
