"""
Preprocess main_data_with_imbalance.csv into data.js for the static website.

Outputs a JavaScript file that defines a global WIND_DATA object containing
parallel arrays for each variable used by the simulation engine.

Sign-convention sanity check (Level 2 example 1) is verified at the bottom.
"""

import json
import os
import sys
from datetime import datetime

import numpy as np
import pandas as pd

CSV_PATH = "main_data_with_imbalance.csv"
OUT_PATH = "data.js"

NEEDED = [
    "datetime_utc",
    "scipher_da_p50_mw",
    "scipher_id_p50_mw",
    "lt_dayahead_price_eur_mwh",
    "mfrr_sa_upward_lv",
    "mfrr_sa_downward_lv",
    "wind_park_possible",
    "final_imbalance_price_latvia",
]


def main():
    print("Reading CSV...", flush=True)
    df = pd.read_csv(CSV_PATH, usecols=NEEDED)
    print(f"  rows: {len(df)}")

    # Verify mFRR up/down are usually identical (single clearing price assumption)
    same = (df["mfrr_sa_upward_lv"] == df["mfrr_sa_downward_lv"]).sum()
    pct = same / len(df) * 100
    print(f"  mFRR up==down in {pct:.2f}% of rows ({same}/{len(df)})")
    diff_mask = (df["mfrr_sa_upward_lv"] != df["mfrr_sa_downward_lv"]) & (
        df["mfrr_sa_upward_lv"].notna() & df["mfrr_sa_downward_lv"].notna()
    )
    n_diff = diff_mask.sum()
    print(f"  rows where they differ (both non-NaN): {n_diff}")
    # Use upward as the single clearing price (assumed equal in spec)
    df["p_mfrr"] = df["mfrr_sa_upward_lv"]

    # Convert kW -> MW for actual production
    df["q_pot"] = df["wind_park_possible"] / 1000.0

    # Drop rows with NaN in any required column
    needed_cols = [
        "scipher_da_p50_mw",
        "scipher_id_p50_mw",
        "lt_dayahead_price_eur_mwh",
        "p_mfrr",
        "q_pot",
        "final_imbalance_price_latvia",
    ]
    before = len(df)
    df = df.dropna(subset=needed_cols).reset_index(drop=True)
    after = len(df)
    print(
        f"  dropped {before - after} NaN rows ({(before - after) / before * 100:.2f}%); "
        f"remaining: {after}"
    )

    # Parse timestamps to derive offset from a fixed start
    df["ts"] = pd.to_datetime(df["datetime_utc"], utc=False)
    start = df["ts"].iloc[0]
    df["idx"] = ((df["ts"] - start).dt.total_seconds() / 60 / 15).astype(int)
    print(f"  start: {start}, end: {df['ts'].iloc[-1]}")
    print(f"  max offset (15-min units): {int(df['idx'].iloc[-1])}")

    # Round to keep file size sane
    da = df["scipher_da_p50_mw"].round(3).tolist()
    iduvw = df["scipher_id_p50_mw"].round(3).tolist()
    pda = df["lt_dayahead_price_eur_mwh"].round(2).tolist()
    pmfrr = df["p_mfrr"].round(2).tolist()
    qpot = df["q_pot"].round(3).tolist()
    pimb = df["final_imbalance_price_latvia"].round(2).tolist()
    offsets = df["idx"].tolist()

    out = {
        "start_iso": start.strftime("%Y-%m-%dT%H:%M:%SZ"),
        "n": len(df),
        "step_min": 15,
        "offsets": offsets,
        "da_forecast": da,
        "id_forecast": iduvw,
        "p_da": pda,
        "p_mfrr": pmfrr,
        "q_pot": qpot,
        "p_imb": pimb,
    }

    js = "// Auto-generated by preprocess.py — do not edit by hand.\n"
    js += "const WIND_DATA = " + json.dumps(out, separators=(",", ":")) + ";\n"
    js += "if (typeof module !== 'undefined') module.exports = WIND_DATA;\n"

    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write(js)

    sz = os.path.getsize(OUT_PATH) / (1024 * 1024)
    print(f"  wrote {OUT_PATH}: {sz:.2f} MB")

    # Print summary statistics for each column (for reference / debugging)
    print()
    print("Summary stats (for sanity):")
    for name, arr in [
        ("da_forecast (MW)", da),
        ("id_forecast (MW)", iduvw),
        ("p_da (EUR/MWh)", pda),
        ("p_mfrr (EUR/MWh)", pmfrr),
        ("q_pot (MW)", qpot),
        ("p_imb (EUR/MWh)", pimb),
    ]:
        a = np.asarray(arr)
        print(
            f"  {name:25s} min={a.min():10.2f} p10={np.percentile(a, 10):10.2f} "
            f"p50={np.percentile(a, 50):10.2f} p90={np.percentile(a, 90):10.2f} "
            f"max={a.max():10.2f}"
        )

    # ===========================================================================
    # SIGN CONVENTION CHECK — replay the two given Level 2 examples
    # ===========================================================================
    print()
    print("Sign-convention manual checks (Level 2 examples from spec):")

    def isp_revenue_l2(F, ID, P_da, P_mfrr, Q_pot, P_imb, X, Y, Z, theta=30.0):
        # Mirrors engine.js after the audit fixes (whole-MW + dn cap + Q_pos).
        import math
        above_X = P_da >= X
        Q_da_sold = math.floor((F if above_X else F * (1 - Y)) + 1e-9)
        Q_with = math.floor((0.0 if above_X else F - Q_da_sold) + 1e-9)
        revision = ID - F
        trusted_raw = Z * revision
        trusted_extra = math.floor(trusted_raw + 1e-9) if trusted_raw > 0 else 0
        Q_up_offer = Q_with + trusted_extra
        Q_dn_offer = Q_da_sold  # curtailment capped at DA
        is_up = P_mfrr >= 1.0
        is_dn = P_mfrr <= -1.0
        Q_up = Q_up_offer if is_up else 0.0
        Q_dn = Q_dn_offer if is_dn else 0.0
        DA_rev = Q_da_sold * P_da
        mFRR_up_rev = Q_up * P_mfrr
        mFRR_dn_rev = -Q_dn * P_mfrr
        Q_pos = Q_da_sold + Q_up - Q_dn  # mFRR-dn reduces position
        Q_short = max(0.0, Q_pos - Q_pot)
        imb_cost = Q_short * P_imb
        flat_cost = Q_short * theta
        total = (DA_rev + mFRR_up_rev + mFRR_dn_rev - imb_cost - flat_cost) * 0.25
        return total, dict(
            Q_da_sold=Q_da_sold,
            Q_with=Q_with,
            trusted=trusted_raw,
            Q_up=Q_up,
            Q_dn=Q_dn,
            DA_rev=DA_rev,
            mFRR_up_rev=mFRR_up_rev,
            mFRR_dn_rev=mFRR_dn_rev,
            Q_short=Q_short,
            imb_cost=imb_cost,
            flat_cost=flat_cost,
        )

    # Example 1: should yield -322.5
    rev1, parts1 = isp_revenue_l2(
        F=20, ID=18, P_da=5, P_mfrr=50, Q_pot=12, P_imb=200, X=10, Y=0.5, Z=0.5
    )
    print(f"  Example 1 expected -322.5 EUR  got {rev1:+.2f} EUR  ", end="")
    print("OK" if abs(rev1 + 322.5) < 1e-6 else "FAIL")
    print(f"    parts: {parts1}")

    # Example 2: should yield 375
    rev2, parts2 = isp_revenue_l2(
        F=20, ID=20, P_da=100, P_mfrr=0, Q_pot=10, P_imb=20, X=10, Y=0.5, Z=0.0
    )
    print(f"  Example 2 expected 375.0 EUR  got {rev2:+.2f} EUR   ", end="")
    print("OK" if abs(rev2 - 375.0) < 1e-6 else "FAIL")
    print(f"    parts: {parts2}")


if __name__ == "__main__":
    main()
